In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [2]:
# 1. Create a 1D and 2D array using Numpy, and print its datatype, shape, and dimension.

In [3]:
array_1d = np.array([1,2,3])
print(array_1d.dtype)
print(array_1d.shape)

int32
(3,)


In [4]:
array_2d = np.array([[1,2,3], [4,5,6]])
print(array_2d.dtype)
print(array_2d.shape)

int32
(2, 3)


In [5]:
# 2. Create a 1D and 2D array with the following initializations

In [6]:
array_1d = np.random.randn(5)
print(array_1d)
array_2d = np.random.randn(5,5)
print(array_2d)

[-0.02324116 -0.46445982 -0.32284706 -0.10203922  0.94658237]
[[-0.14463603  0.99505775  0.16691386 -0.12498833  0.11661956]
 [ 0.96344426  1.27581437  0.97799817  0.08675233 -1.11134589]
 [-1.63709191  0.79373408 -1.27065101  1.58077736 -0.95572892]
 [ 0.76307834  0.16149646 -3.2245366   1.89812426  1.70661974]
 [-0.49707147 -0.70595163 -0.76159563  2.08634055 -0.65205733]]


In [7]:
# diagonal
print(array_2d.diagonal())

[-0.14463603  1.27581437 -1.27065101  1.89812426 -0.65205733]


In [8]:
# first and last
print(f"1D: first = {array_1d[0]}, last = {array_1d[-1]}")
print(f"2D: first = {array_2d[0]}, last = {array_2d[-1]}")

1D: first = -0.023241155793887674, last = 0.9465823714503184
2D: first = [-0.14463603  0.99505775  0.16691386 -0.12498833  0.11661956], last = [-0.49707147 -0.70595163 -0.76159563  2.08634055 -0.65205733]


In [9]:
# 2nd row, 2nd column
print(array_2d[1][1])
print(array_2d[1,1])

1.2758143731621288
1.2758143731621288


In [10]:
# Number of elements
print(f"Number of elements: 1D: {array_1d.size}")
print(f"Number of elements: 2D: {array_2d.size}")

Number of elements: 1D: 5
Number of elements: 2D: 25


In [11]:
# 3. Find the following operations on a matrix:

In [12]:
array1 = np.array([[1,1],[0,4]])
array2 = np.array([[2,0],[0,3]])
print(array1)
print(array2)

[[1 1]
 [0 4]]
[[2 0]
 [0 3]]


In [13]:
# Determinant
print(np.linalg.det(array1))
print(np.linalg.det(array2))

4.0
6.0


In [14]:
# Addition
print(array1 + array2)

[[3 1]
 [0 7]]


In [15]:
# Subtraction
print(array1 - array2)

[[-1  1]
 [ 0  1]]


In [16]:
# multiplication
print(array1 * array2) # element-wise
print(array1 @ array2) # matrix multiplication

[[ 2  0]
 [ 0 12]]
[[ 2  3]
 [ 0 12]]


In [17]:
# Division (multiplication by inverse)
inv = np.linalg.inv(array2)
print(inv)
print(array1 @ inv)

[[0.5        0.        ]
 [0.         0.33333333]]
[[0.5        0.33333333]
 [0.         1.33333333]]


In [18]:
# Transpose
print(array1.T)
print(array2.T)

[[1 0]
 [1 4]]
[[2 0]
 [0 3]]


In [19]:
# cross product
print(np.cross(array1, array2))

[-2  0]


In [20]:
array_1d = np.array([1,2])
array_2d = np.array([[3,4], [5,6]])

In [21]:
# dot product 
print(f"1D array = {array_1d}")
print(f"2D array = {array_2d}")

1D array = [1 2]
2D array = [[3 4]
 [5 6]]


In [22]:
# 1d by 1d
print(np.dot(array_1d, array_1d))
# 1d by 2d
print(np.dot(array_1d, array_2d))
# 2d by 1d
print(np.dot(array_2d, array_1d))
# 2d by 2d
print(np.dot(array_2d, array_2d))

5
[13 16]
[11 17]
[[29 36]
 [45 56]]


In [23]:
# 4. Print range values in 1D and 2D arrays

In [24]:
array_1d = np.linspace(1, 5, 5)
print(array_1d)

[1. 2. 3. 4. 5.]


In [25]:
array_2d = np.linspace((1, 6), (5, 10), 5).T
print(array_2d)

[[ 1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10.]]


In [26]:
print(array_1d[1:4])
print(array_1d[2:])
print(array_1d[:2])

[2. 3. 4.]
[3. 4. 5.]
[1. 2.]


In [27]:
print(array_2d[1:4])
print(array_2d[1:])
print(array_2d[:1])
print(array_2d[:, 2:4])
print(array_2d[:1,1])

[[ 6.  7.  8.  9. 10.]]
[[ 6.  7.  8.  9. 10.]]
[[1. 2. 3. 4. 5.]]
[[3. 4.]
 [8. 9.]]
[2.]


In [28]:
# 5. Reshape an array

In [29]:
print(array_2d.reshape((1, 10)))

[[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]]


In [30]:
print(array_1d.reshape((5, 1)))

[[1.]
 [2.]
 [3.]
 [4.]
 [5.]]


In [31]:
array_2d.reshape((2,5))

array([[ 1.,  2.,  3.,  4.,  5.],
       [ 6.,  7.,  8.,  9., 10.]])

In [32]:
# 6. Find the following statistical measures

In [33]:
# Min
print(array_2d.min())

1.0


In [34]:
# Max
print(array_2d.max())

10.0


In [35]:
# Mean
print(array_2d.mean())

5.5


In [36]:
# Sum
print(array_2d.sum())

55.0


In [37]:
# Median
print(np.median(array_2d))

5.5


In [38]:
# Mode
unique, counts = np.unique(array_2d, return_counts=True)
print(np.argmax(counts))

0


In [39]:
# standard deviation
print(np.std(array_2d))

2.8722813232690143


In [40]:
# 7. Create a boolean mask for values greater than 5:
mask = array_2d > 5
print(mask)

[[False False False False False]
 [ True  True  True  True  True]]


In [41]:
# Use the mask to filter out values less than or equal to 5
print(array_2d[mask])

[ 6.  7.  8.  9. 10.]


In [42]:
# Count the number of values greater than 5
print(np.count_nonzero(mask))

5


In [43]:
# 8. Fancy Indexing

In [44]:
# Use fancy indexing to access elements at specific indices.
print(array_2d)
print(array_2d[[1]])
print(array_2d[1][[2, 3, 4]])
print(array_2d[[0, 1, 1], [0, 2 ,3]])

[[ 1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10.]]
[[ 6.  7.  8.  9. 10.]]
[ 8.  9. 10.]
[1. 8. 9.]


In [45]:
# Create a new array by selecting every other element.
print(array_1d)
print(array_1d[::2])

[1. 2. 3. 4. 5.]
[1. 3. 5.]


In [46]:
# 9. Structured Array:

In [47]:
# Create a structured array to store information about students (name, age, and grade).
structured_arr = x = np.array([], dtype=[('name', 'U10'), ('age', 'i4'), ('grade', 'f4')])

In [48]:
# Create a few sample students.
structured_arr = np.insert(structured_arr, 0, ('Rex', 20, 8.))

In [49]:
structured_arr = np.insert(structured_arr, 0, ('Lex', 19, 9.2))

In [50]:
print(structured_arr)

[('Lex', 19, 9.2) ('Rex', 20, 8. )]


In [51]:
# Access and modify specific fields of the structured array.
print(structured_arr[0]['name'])
structured_arr[0]['name'] = 'Tex'
print(structured_arr)

Lex
[('Tex', 19, 9.2) ('Rex', 20, 8. )]


In [52]:
# 10. Linear Regression:
data = pd.read_excel("data.xlsx")
print(data)

   x1  x2   y
0   2   1  60
1   3   2  65
2   4   2  70
3   5   3  75
4   6   3  80


In [53]:
X = data[['x1', 'x2']]
X.insert(0, '1', 1)
print(X)

   1  x1  x2
0  1   2   1
1  1   3   2
2  1   4   2
3  1   5   3
4  1   6   3


In [54]:
Y = data['y']
print(Y)

0    60
1    65
2    70
3    75
4    80
Name: y, dtype: int64


In [55]:
B = np.linalg.inv(X.T @ X) @ X.T @ Y
print(B)

0    5.000000e+01
1    5.000000e+00
2   -4.263256e-13
dtype: float64


In [56]:
def y_hat(x1, x2):
    return np.dot(B, np.array([1, x1, x2]))

In [58]:
print(y_hat(2, 1))

59.999999999999474
